version: '3.3'

services:

  proxy:
    image: traefik:v2.2
    ports:
      - 80:80
#   deploy:
    labels:
        # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      - traefik.http.routers.proxy-http.entrypoints=http
      - traefik.http.routers.proxy-http.rule=Host(`192.168.0.6`)
      - traefik.http.routers.proxy-http.service=api@internal
      - traefik.http.services.proxy.loadbalancer.server.port=8080
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api
    networks:
      - netext
networks:
  netext:
#    external: true