version: '3.9'

services:
  proxy:
    image: traefik:v2.5
    deploy:
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --providers.docker.swarmmode
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - netext

  base_image: 
    image: php-fpm
    # expose:
    #   - 80
    deploy:
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
#        - traefik.http.routers.php-fpm.entrypoints=web
        - traefik.http.routers.php-fpm.rule=Host(`192.168.0.6`)  
        - traefik.http.services.php-fpm.loadbalancer.server.port=80
    volumes:
      - ./speedtest/servers.json:/servers.json
#      - ./speedtest/telemetry_settings.php:/speedtest/results/telemetry_settings.php
    environment:
      - TELEMETRY=true
      - TITLE=test
      - MODE=frontend
      - PASSWORD=password
      - ENABLE_ID_OBFUSCATION=true
      - REDACT_IP_ADDRESSES=false
      - DB_TYPE=postgresql
      - DB_NAME=speed
      - DB_HOSTNAME=postgresql 
      - DB_USERNAME=admin
      - DB_PASSWORD=Abc

    networks:
      - netext

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Abc
      POSTGRES_DB: speed
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./speedtest/results/telemetry_postgresql.sql:/docker-entrypoint-initdb.d/telemetry_postgresql.sql
    networks:
      - netext

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - netext

networks:
  netext:
    external: true
volumes:
  db_data: